### ISSUE TITLE
[Feature] Define tunnels without using the API.

### ISSUE THREAD

**Issue by TheDeafCreeper** [whimxiqal/journey#43]
Having the ability to define tunnels without needing to use the API, such as with a command or configuration options, would allow people with less development skills to utilize the feature.

Main places I can image you'd want to be able to define tunnels manually would be:
- When you use Command Blocks to teleport.
- If you're using a plugin that allows teleportation with no integration addon.

How I imagine implementation would go would either be a command with a format similar to this:
`/registertunnel NAME xOrigin yOrigin zOrigin worldName xDest yDest zDest worldName`

or a configuration file with entries similar to this (yaml format example):
```yaml
tunnels:
  name:
    origin:
      x: 0
      y: 0
      z: 0
      world: world
    destination:
      x: 0
      y: 0
      z: 0
      world: world_the_nether
```
